version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
    target-branch: staging

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: staging
